### ISSUE TITLE
"KeyError: 'ROS_WORKSPACE'" following readme instructions

### ISSUE THREAD

**Issue by gavanderhoorn** [git-afsantos/haros_tutorials#3]
Following the instructions in the [readme](https://github.com/git-afsantos/haros_tutorials/blob/006d670a3d5f2f2b9944ec9f33c7cd769793c49f/README.md), `haros full -p my_index.yaml` results in the following:

```python-traceback
Traceback (most recent call last):
  File "/home/user/venv_haros/bin/haros", line 10, in <module>
    sys.exit(main())
  File "/home/user/venv_haros/local/lib/python2.7/site-packages/haros/haros.py", line 725, in main
    if launcher.launch(argv = argv):
  File "/home/user/venv_haros/local/lib/python2.7/site-packages/haros/haros.py", line 144, in launch
    settings = HarosSettings.parse_from(self.USER_SETINGS)
  File "/home/user/venv_haros/local/lib/python2.7/site-packages/haros/data.py", line 486, in parse_from
    cpp_includes = cpp_includes, cpp_compile_db = cpp_compile_db)
  File "/home/user/venv_haros/local/lib/python2.7/site-packages/haros/data.py", line 454, in __init__
    self.workspace = workspace or self.find_workspace()
  File "/home/user/venv_haros/local/lib/python2.7/site-packages/haros/data.py", line 504, in find_workspace
    raise KeyError("ROS_WORKSPACE")
KeyError: 'ROS_WORKSPACE'
```

even after

```bash
source /opt/ros/kinetic/setup.bash
export ROS_PACKAGE_PATH=`pwd`:$ROS_PACKAGE_PATH
```
where `pwd` is the location where I cloned `git-afsantos/haros_tutorials`.

**Comment by git-afsantos** [comment]
I am not at the computer right now, but that section of the code is meant to replicate the behaviour of `roscd`, basically. Does `roscd` work for you, in that shell?

In any case, I should probably change it so that the behaviour is not mandatory.

**Comment by gavanderhoorn** [comment]
Yes.

Without any arguments, takes me to `/opt/ros/kinetic`.

With `roscd fictibot_msgs` takes me to the `fictibot_msgs` in the clone.

**Comment by git-afsantos** [comment]
The documentation for this repository has changed.
The previous instructions are now obsolete, and the problem should not occur.
